INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('인텔리제이 강의듣기', 'Ch01 끝내기', 'IN_PROGRESS', CURRENT_TIMESTAMP + INTERVAL '1' DAY);

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('인텔리제이 강의듣기', 'Ch02 끝내기', 'TODO', CURRENT_TIMESTAMP + INTERVAL '2' DAY);